# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 9335122ff5248f66b5cfbad91a99eeb9e754ea89ed49f077ec6b2b06f8808f33085b45d28bcbb73b24f2c1080d315a0245d55cc55ff7346cfa25f31391b74114

test:
  secret_key_base: fbba8dd9a3c4e656143162f878b713ac909d85d4feb0a080b931e68caedd10341a17edc0edb21bc4c4294607c496fad9992c58f6482c9f77a80e4c775dde029f

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
